"""random-only

Revision ID: 8fa3543a4fca
Revises:
Create Date: 2025-08-09 13:09:01.312320

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8fa3543a4fca"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name="users_pkey"),
    )
    op.create_table(
        "random_problems",
        sa.Column("random_problem_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("latitude", sa.Double(precision=53), nullable=False),
        sa.Column("longitude", sa.Double(precision=53), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("ended_at", sa.DateTime(), nullable=True),
        sa.Column("image_url", sa.String(length=255), nullable=True),
        sa.CheckConstraint(
            "status::text = ANY (ARRAY['pending'::character varying,\n    \
                        'completed'::character varying, 'given_up'::character varying]::text[])",
            name="random_problems_status_check",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name="random_problems_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("random_problem_id", name="random_problems_pkey"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("random_problems")
    op.drop_table("users")
    # ### end Alembic commands ###
