name: Ruff Check

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  ruff:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run ruff linter
      uses: astral-sh/ruff-action@v3
      with:
        args: "check"
    
    - name: Run ruff formatter check
      uses: astral-sh/ruff-action@v3
      with:
        args: "format --check --diff"
